const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECT_PRODUCT: "SELECT_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
};

export default ActionTypes;
